using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace STS.General.Diagnostics
{
    /// <summary>
    /// Provides an IO monitoring for a process.
    /// </summary>
    public class IOMonitor
    {
        private Timer timer;

        private PerformanceCounter writesCounter;
        private PerformanceCounter readsCounter;
        private PerformanceCounter dataCounter;

        private bool monitorIOWrites;
        private bool monitorIOReads;
        private bool monitorIOData;

        private long monitorPerionInMilliseconds;

        public IOMonitor(bool monitorIOWrites, bool monitorIOReads, bool monitorIOData, int monitorPeriodInMilliseconds)
        {
            if (!monitorIOWrites && !monitorIOReads && !monitorIOData)
                throw new ArgumentException("At least one flag has to be true.");

            this.monitorIOWrites = monitorIOWrites;
            this.monitorIOReads = monitorIOReads;
            this.monitorIOData = monitorIOData;

            this.monitorPerionInMilliseconds = monitorPeriodInMilliseconds;

            string processName = Process.GetCurrentProcess().ProcessName;

            if(monitorIOWrites)
                writesCounter = new PerformanceCounter("Process", "IO Write Bytes/sec", processName);
            if(monitorIOReads)
                readsCounter = new PerformanceCounter("Process", "IO Read Bytes/sec", processName);
            if(monitorIOData)
                dataCounter = new PerformanceCounter("Process", "IO Data Bytes/sec", processName);

            timer = new Timer(DoMonitor, null, Timeout.Infinite, MonitorPeriodInMilliseconds);
        }

        public IOMonitor(int monitorPeriodInMilliseconds = 1000)
            :this(true, true, true, monitorPeriodInMilliseconds)
        {
        }

        private void DoMonitor(object state)
        {
            if (monitorIOWrites)
            {
                IOWriteBytes = writesCounter.NextValue();

                if (IOWriteBytes > PeakIOWriteBytes)
                    PeakIOWriteBytes = IOWriteBytes;
            }

            if (monitorIOReads)
            {
                IOReadBytes = readsCounter.NextValue();

                if (IOReadBytes > PeakIOReadBytes)
                    PeakIOReadBytes = IOReadBytes;
            }

            if (monitorIOData)
            {
                IODataBytes = dataCounter.NextValue();

                if (IODataBytes > PeakIODataBytes)
                    PeakIODataBytes = IODataBytes;
            }
        }

        public void Start()
        {
            timer.Change(0, MonitorPeriodInMilliseconds);
        }

        public void Stop()
        {
            timer.Change(Timeout.Infinite, Timeout.Infinite);
        }

        public void Reset()
        {
            IOWriteBytes = 0;
            IOReadBytes = 0;
            IODataBytes = 0;

            PeakIOWriteBytes = 0;
            PeakIOReadBytes = 0;
            PeakIODataBytes = 0;
        }

        /// <summary>
        /// Gets or sets the interval between every measure.
        /// </summary>
        public long MonitorPeriodInMilliseconds
        {
            get { return monitorPerionInMilliseconds; }
            set
            {
                monitorPerionInMilliseconds = value;
                timer.Change(0, monitorPerionInMilliseconds);
            }
        }

        /// <summary>
        /// Shows the rate, in incidents per second, at which the process was writing bytes to I/O operations. 
        /// It counts all I/O activity generated by the process including file, network, and device I/Os.
        /// </summary>
        public float IOWriteBytes { get; private set; }

        /// <summary>
        /// Shows the rate, in incidents per second, at which the process was reading bytes from I/O operations. 
        /// It counts all I/O activity generated by the process including file, network, and device I/Os.
        /// </summary>
        public float IOReadBytes { get; private set; }

        /// <summary>
        /// Shows the rate, in incidents per second, at which the process was reading and writing bytes in I/O operations. 
        /// It counts all I/O activity generated by the process including file, network, and device I/Os.
        /// </summary>
        public float IODataBytes { get; private set; }

        /// <summary>
        /// Gets the peak I/O write bytes value.
        /// </summary>
        public float PeakIOWriteBytes { get; private set; }

        /// <summary>
        /// Gets the peak I/O read bytes value.
        /// </summary>
        public float PeakIOReadBytes { get; private set; }

        /// <summary>
        /// Gets the peak I/O data bytes value.
        /// </summary>
        public float PeakIODataBytes { get; private set; }
    }
}
